### ISSUE TITLE
Sometime the build scan url isn't extracted

### ISSUE THREAD

**Issue by lacasseio** [eskatos/gradle-command-action#26]
There seems to be a problem in the logic here: https://github.com/eskatos/gradle-command-action/blob/master/src/execution.ts#L21-L30

It seems that the next line is sometimes empty which causes the publish URL scrapping to miss the real line with the URL. I can recommend extracting the first instance of a line starting with `http`. Alternatively, it could be the other check that fails where the line doesn't exactly start with HTTP. Unfortunately, there isn't enough logging to figure out where the failure is happening.

**Comment by lacasseio** [comment]
Here is an example, the statuses mark with Details properly detected the build scan URL while the other ones have a build scan URL but weren't extracted:

<img width="719" alt="Screen Shot 2020-07-19 at 1 04 40 PM" src="https://user-images.githubusercontent.com/22181740/87873287-2d411380-c98e-11ea-981f-0d244bda3e20.png">

**Comment by eskatos** [comment]
Hey Daniel 👋 
Thanks for the report, I simplified the build scan url scraping.
Please try again and tell me how it goes, we'll reopen this issue if needed.
