### ISSUE TITLE
Cache generated-gradle-jars into a tool-cache as well

### ISSUE THREAD

**Issue by vlsi** [eskatos/gradle-command-action#27]
Have you tried caching generated-gradle-jars into `tool-cache` as well?

In other words:
1. Download Gradle
1. Execute it so it generates `.gradle/caches/6.6/generate-gradle-jars/...`
1. Ensure `generated-gradle-jars` is cached into `tool-cache` (e.g. copy it to `gradle` location)
1. As the tool is unpacked from the cache, copy `generated-gradle-jars` accordingly

See https://github.com/gradle/gradle/issues/13982

Update: `tool-cache` does not cache files across job executions in GitHub runners (see https://github.com/actions/toolkit/issues/58#issuecomment-521672239), so currently tool-cache is not useful for caching `gradle-generated-jars`

**Comment by eskatos** [comment]
There's another aspect to this. Gradle can generate three different JARs in that directory, the `gradle-api` jar, the `gradle-kotlin-dsl-extensions` jar and the `gradle-test-kit` jar. Those are generated on-demand so which jars get generated depends on what the run build does.

**Comment by vlsi** [comment]
Thanks for the clarification.

As `tool-cache` is not reused across GitHub runners, it makes little sense to cache it into the `tool-cache`, so I close the issue as there's nothing to do :-(

It looks like the way to go is to solve https://github.com/gradle/gradle/issues/13982 somehow (e.g. use classpath-only jar instead of a full-blown jar)
