### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by Jaimss** [eskatos/gradle-command-action#28]
```yaml
name: Check if it builds.

on:
  pull_request:
    branches: [ master ]

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: test build
```
Gives this error:
```
Run eskatos/gradle-command-action@v1
(node:2526) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Wrapper installation cache not found, expect a Gradle distribution download.
##[error]Unable to locate executable file: /home/runner/work/mcutils/mcutils/gradlew. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```
See [this](https://github.com/Jaimss/mcutils/runs/999404889?check_suite_focus=true) for the full action.

Not sure how to specifcy the path to my gradlew

**Comment by vlsi** [comment]
@Jaimss , your repository misses `gradle/wrapper/gradle-wrapper.properties` file, so `gradle-command-action` can't really predict which Gradle version do you want to execute.

Have you tried adding `gradle/wrapper/...` to the Git sources?
Have you tried adding `gradle-version: 6.6` to the `gradle-command-action`?

**Comment by Jaimss** [comment]
I actually had removed the `gradle/wrapper` from my `.gitignore`, but maybe since it wasn't in my master branch yet, it was causing me issues.

Anyways, adding the gradle-version has worked. Thanks for the help and quick response!
