### ISSUE TITLE
build-root-directory is not considered

### ISSUE THREAD

**Issue by kuniss** [eskatos/gradle-command-action#42]
May be I'm doing something wrong but adding `build-root-directory` pointing to a sub directory in my repository where the Gradle wrapper lives does not get effective and the build fails.

The workflow file is https://github.com/kuniss/ScalaFlow/blob/master/.github/workflows/build.yml
An example of a failed build running this workflow can be found here: https://github.com/kuniss/ScalaFlow/actions/runs/438808438

Thanks in advance!

**Comment by eskatos** [comment]
Hi @kuniss,

`build-root-directory` allows you to set what directory is used to find the build you want to use.
`wrapper-directory` allows you to set what directory is used to locate the Gradle wrapper.

In your case you need both to be set:

```
wrapper-directory: FlowDesignInScala
build-root-directory: FlowDesignInScala
```

HTH

**Comment by eaxdev** [comment]
@eskatos I have the same error. 
My workflow: https://github.com/eaxdev/otus_java_2020_12/blob/master/.github/workflows/gradle-ci-build.yml
My result: https://github.com/eaxdev/otus_java_2020_12/runs/1601908829?check_suite_focus=true

I want to use gradle wrapper. And it not working for me

**Comment by kuniss** [comment]
Thanks! :+1: 
Worked very well for me. I'm going to close this issue.

@eaxdev Your issue is different! Your gradle files are already located in your project's root directory. 
I guess, your `gradlew` shell script has no executable permission. 

You may achieve this under Linux through and a subsequent commit/push
```
chmod +x gradlew
```

Under Windows you have to rely on git at the command line:
```
git update-index --chmod=+x gradlew
```
