### ISSUE TITLE
Gradle 7 not found

### ISSUE THREAD

**Issue by 24glinka** [eskatos/gradle-command-action#45]
Hi, I run a build with gradle-version: 7.0. I got an error: the version wasn't recognized. Is there a way to call it in this way or should we wait for an upgrade (using in the meantime the wrapper)? Regards

**Comment by mateuszkwiecinski** [comment]
Hey @24glinka, can you share related part of your setup and full error message? 
I had similar problem and it turned out version `x.y.z` is recognized properly by Github Actions, but `x.y` not. The workaround was to wrap version with `"`, so instead of `7.0` I had to use `"7.0"`

I'm also experiencing issues like:
```

Run eskatos/gradle-command-action@v1
  with:
    build-root-directory: sample/android
    gradle-version: 7.0
    arguments: projectCoverage -PuseMavenLocal
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.11-9/x64
(node:1585) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Downloading services.gradle.org/distributions/gradle-7.0-bin.zip
Downloaded at /home/runner/gradle-provision-tmpdir/downloads/gradle-7.0-bin.zip, size 4058
Error: invalid signature: 0x4f44213c
````
which happens only with Gradle 7.0, but I won't be able to help then 👀

**Comment by 24glinka** [comment]
This is the initial part of the configuration: now the version is commented, so of course when I tested it was uncommented. A workaround has been using the gradlew, specifying the version. But I was expecting the version was recognized.

`build:    name: Build phase    runs-on: ubuntu-18.04    steps:    - uses: actions/checkout@v2    - uses: actions/setup-node@v1      with:        node-version: '11.15.0'    - name: Set up JDK 15      uses: actions/setup-java@v1      with:        java-version: 15    #- name: Gradle 6.8.3    #  uses: eskatos/gradle-command-action@v1    #  with:    #    gradle-version: 6.8.3

`

**Comment by mateuszkwiecinski** [comment]
According to what you pasted you've been trying to run the script with gradle `6.8.3`, not `7.0`. 
I got lost a bit now. What precisely doesn't work and what error does it show? 

Can you paste a formatted config so it is easier for everyone to see what happens there?
```
build: 
	name: Build phase 
	runs-on: ubuntu-18.04 
	steps: 
	  - uses: actions/checkout@v2 
	  
	  - uses: actions/setup-node@v1 
	  	  with: 
	  	   node-version: '11.15.0' 
		   
	   - name: Set up JDK 15 
	  	  uses: actions/setup-java@v1 
	  	  with: 
	  	   java-version: 15 
	  	  
	   - name: Gradle 6.8.3
	  	  uses: eskatos/gradle-command-action@v1 
	  	  with: 
	  	   gradle-version: 6.8.3
```


From my experience:
`gradle-version: 6.8.3` - works ✅ 
`gradle-version: "6.8.3"` - works ✅ 
`gradle-version: 7.0` - doesn't ❌
`gradle-version: "7.0"` - works ✅

**Comment by 24glinka** [comment]
I put the code in formatted style, but that's was the result. The same problem was for 6.8.3 as well, so for me: 6.8.3 not works; 7.0 not works.

Now I tried 7.0.2 and the problem doesn't appear.

**Comment by mateuszkwiecinski** [comment]
Can you provide a repro project? I should be able to help. This action works for me for all gradle versions 🤔

**Comment by 24glinka** [comment]
With 7.0.2 works. Closing issue.
